### ISSUE TITLE
Lines shrink when both org-indent-mode and display-line-numbers-mode are on

### ISSUE THREAD

**Issue by chuxubank** [casouri/valign#17]
org-indent-mode: on
<img width="829" alt="image" src="https://user-images.githubusercontent.com/17001575/100812650-81015480-3478-11eb-84e5-4a82b981fe7d.png">

org-indent-mode: off
<img width="802" alt="image" src="https://user-images.githubusercontent.com/17001575/100812800-d5a4cf80-3478-11eb-8d72-7b28fb124120.png">

**Comment by chuxubank** [comment]
If turn on `org-indent-mode` after `valign-mode` is on, this error shows up:
```elisp
Debugger entered--Lisp error: (valign-parse-error "Missing the right bar (|)")
  signal(valign-parse-error ("Missing the right bar (|)"))
  valign-table-1()
  valign-table-maybe(nil t)
  valign-region(2427 2518)
  #f(compiled-function (fun) #<bytecode 0x1fe56aef6035>)(valign-region)
  run-hook-wrapped(#f(compiled-function (fun) #<bytecode 0x1fe56aef6035>) valign-region)
  jit-lock--run-functions(2427 2518)
  jit-lock-fontify-now(2018 2518)
  jit-lock-function(2018)
  window-text-pixel-size(#<window 3 on test.org> 2018 2019)
  valign--pixel-width-from-to(2018 2019)
  valign--table-2()
  valign-table-maybe(nil t)
  valign-region()
  valign--buffer-advice()
  run-hooks(org-indent-mode-hook org-indent-mode-on-hook)
  org-indent-mode(toggle)
  funcall-interactively(org-indent-mode toggle)
  call-interactively(org-indent-mode record nil)
  command-execute(org-indent-mode record)
  execute-extended-command(nil "org-indent-mode" #("org-indent-mod" 0 14 (ws-butler-chg chg)))
  funcall-interactively(execute-extended-command nil "org-indent-mode" #("org-indent-mod" 0 14 (ws-butler-chg chg)))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by casouri** [comment]
That's probably because you turned on debug-on-error. Normally that signal is caught.

**Comment by casouri** [comment]
The problem isn't in org indent mode but rather display-line-numbers-mode. I got it to work with org-indent-mode or display-line-numbers-mode alone, but when both are enabled there's some weird effect on how Emacs measures pixel width of a piece of text that I didn't figure out yet. So for now all you can do is to either disable line-numbers-mode or org-indent-mode.

**Comment by chuxubank** [comment]
After turning off line numbers via `doom/toggle-line-numbers`, this error disappeared.
Everything looks nice, thanks!

**Comment by casouri** [comment]
I'll try to get it to work when both modes are enabled, so let's keep this open.

**Comment by Imymirror** [comment]
I use doom-emacs.
when I turn **display-line-numbers-mode** off and just turn  **org-indent-mode** on, the issue still exist. 

**display-line-numbers-mode** and **org-indent-mode** both on : 
![image](https://user-images.githubusercontent.com/52570325/100838020-ae67f580-34ac-11eb-943a-1a5876023f2e.png)

**display-line-numbers-mode** off and **org-indent-mode** on:
![image](https://user-images.githubusercontent.com/52570325/100838093-cd668780-34ac-11eb-8c52-dc527098a895.png)

**Comment by casouri** [comment]
Have you tried realigning by pressing tab?

**Comment by Imymirror** [comment]
I didn't do anything, My feedback problem (text below the dividing line) has been solved!, it doesn't exist! now it works perfectly, i don't know what happen. 

---------------

> I use doom-emacs.
> when I turn **display-line-numbers-mode** off and just turn **org-indent-mode** on, the issue still exist.
> 
> **display-line-numbers-mode** and **org-indent-mode** both on :
> ![image](https://user-images.githubusercontent.com/52570325/100838020-ae67f580-34ac-11eb-943a-1a5876023f2e.png)
> 
> **display-line-numbers-mode** off and **org-indent-mode** on:
> ![image](https://user-images.githubusercontent.com/52570325/100838093-cd668780-34ac-11eb-8c52-dc527098a895.png)

**Comment by casouri** [comment]
Hmmm ok. Anyway, that's good news ;-)

**Comment by Stebalien** [comment]
I can reproduce:

```org
* Foo
** Bar
*** Baz
| foo   | bar           | baz      |
| thing | (foo bar baz) | bla      |
| foo   | bar           | asdfasdf |
| <0>   |               |          |
```

Then run:

```org
(org-indent-mode 1)
(org-table-shrink)
(valign-mode)
```

That yields:

![2020-12-05-214419_508x313_scrot](https://user-images.githubusercontent.com/310393/101272659-0cae0600-3743-11eb-9006-7aed49b6c599.png)

**Comment by stormwatch** [comment]
# Line numbers and Org indent
![line numbers and org indent](https://user-images.githubusercontent.com/824211/102365424-4d551d00-3f96-11eb-88ca-76852b688003.png)

# Line numbers
![line numbers](https://user-images.githubusercontent.com/824211/102364293-0adf1080-3f95-11eb-84a8-cb69ec4bf0e6.png)

# Org indent
![indent](https://user-images.githubusercontent.com/824211/102364298-0b77a700-3f95-11eb-8cee-f5466e2b226a.png)
very subtle

# Line Numbers and Org indent toggled off
![all off](https://user-images.githubusercontent.com/824211/102364302-0c103d80-3f95-11eb-9645-2e6646d8c1b1.png)

_toggling variable pitch mode doesn't affect the results_

**Comment by IceAsteroid** [comment]
It's been a while.

I'm using vanilla emacs, can confirm this still persists in version 29.4, when `display-line-numbers-mode` is turned on for an org-mode buffer.

It works fine until the org-table is modified and re-aligned with tab. 

Is there still no solution for this?

**Comment by casouri** [comment]
Unfortunately, yes. If SomeOne™ can look into this, that'll be great. Otherwise I don't thin this will be fixed anytime soon.

**Comment by IceAsteroid** [comment]
> Unfortunately, yet. If SomeOne™ can look into this, that'll be great. Otherwise I don't thin this will be fixed anytime soon.

Okay.

----------------

To further elaborate, in my case, the `org-indent-mode` isn't turned on, but `display-line-numbers-mode` is turned on.

**Comment by IceAsteroid** [comment]
> Unfortunately, yet. If SomeOne™ can look into this, that'll be great. Otherwise I don't thin this will be fixed anytime soon.

Okay.

----------------

To further elaborate, in my case, the `org-indent-mode` isn't turned on, but `display-line-numbers-mode` is turned on.

## Update

The culprit seems to be setting font size by ratio like `:height 0.8`, rather than an integer number `:height 110`. After changing all the font sizes of faces for line-number and the font used in the buffer, the problem is fixed.

But valign still cannot align the table perfectly, this is same for both cases where `display-line-numbers-mode` and `org-indent-mode` are not turned on, or turned on.


**`display-line-numbers-mode` & `org-indent-mode` & `valign-mode` all turned on**

![Image](https://github.com/user-attachments/assets/bbd92086-8b7a-4e7b-bd39-aabb81bcb837)

**`display-line-numbers-mode` & `org-indent-mode` turned off & `valign-mode` turned on with hitting tabs to reformat**

![Image](https://github.com/user-attachments/assets/ff01fb4a-3d3f-43c1-937b-74cdc50a8b6a)


**`display-line-numbers-mode` & `org-indent-mode` & `valign-mode` all turned off**

![Image](https://github.com/user-attachments/assets/b6f9e057-3958-4563-b469-5e08ca9d27f3)
